# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/linux-java-to-cosmosdb-mongo"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/linux-nodejs-to-cosmosdb-mongo"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/linux-netcore-to-cosmosdb-mongo"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/linux-python-to-cosmosdb-mongo"
    schedule:
      interval: "weekly"
